import PropTypes from "prop-types";

const formatReturn = (value) => {
  if (value === null || value === undefined) return "N/A";
  const sign = value > 0 ? "+" : "";
  return `${sign}${value.toFixed(2)}%`;
};

const formatConfidence = (value) => {
  if (value === null || value === undefined) return "N/A";
  return `${Math.round(value * 100)}%`;
};

const PredictionHistory = ({ history, loading, error, onRefresh }) => {
  if (loading) {
    return (
      <div className="card p-4">
        <p className="text-sm text-[var(--app-muted)]">Loading history...</p>
      </div>
    );
  }

  return (
    <div className="card p-4">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h3 className="text-lg font-semibold text-[var(--app-text)]">
            Prediction History
          </h3>
          <p className="text-sm text-[var(--app-muted)]">
            Recent model-backed signals generated by your account.
          </p>
        </div>
        <button type="button" className="btn-secondary" onClick={onRefresh}>
          Refresh
        </button>
      </div>

      {error && (
        <div className="mt-4 rounded-lg bg-red-50 px-3 py-2 text-sm text-red-700 dark:bg-red-900/30 dark:text-red-200">
          {error}
        </div>
      )}

      {!history.length ? (
        <div className="mt-4 rounded-lg border border-[var(--app-border)] px-4 py-8 text-center">
          <p className="text-sm text-[var(--app-muted)]">
            No prediction history yet. Select an asset to generate your first signal.
          </p>
        </div>
      ) : (
        <div className="mt-4 overflow-x-auto">
          <table className="min-w-[680px] w-full text-left text-sm">
            <thead className="text-xs uppercase text-[var(--app-muted)]">
              <tr>
                <th className="py-2 pr-4">Date</th>
                <th className="py-2 pr-4">Asset</th>
                <th className="py-2 pr-4">Signal</th>
                <th className="py-2 pr-4">Return</th>
                <th className="py-2 pr-4">Confidence</th>
              </tr>
            </thead>
            <tbody>
              {history.map((row) => (
                <tr key={row.id} className="border-t border-[var(--app-border)]">
                  <td className="py-2 pr-4 text-[var(--app-muted)]">
                    {row.timestamp || "-"}
                  </td>
                  <td className="py-2 pr-4 font-medium text-[var(--app-text)]">
                    {row.asset}
                  </td>
                  <td className="py-2 pr-4 text-[var(--app-muted)]">{row.signal}</td>
                  <td className="py-2 pr-4 text-[var(--app-muted)]">
                    {formatReturn(row.expected_return)}
                  </td>
                  <td className="py-2 pr-4 text-[var(--app-muted)]">
                    {formatConfidence(row.confidence)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

PredictionHistory.propTypes = {
  history: PropTypes.arrayOf(
    PropTypes.shape({
      id: PropTypes.number.isRequired,
      asset: PropTypes.string.isRequired,
      signal: PropTypes.string.isRequired,
      expected_return: PropTypes.number,
      confidence: PropTypes.number,
      timestamp: PropTypes.string,
    }),
  ),
  loading: PropTypes.bool,
  error: PropTypes.string,
  onRefresh: PropTypes.func,
};

PredictionHistory.defaultProps = {
  history: [],
  loading: false,
  error: "",
  onRefresh: () => {},
};

export default PredictionHistory;
